minimumReleaseAgeExclude:
  - '@arkade-os/boltz-swap@0.3.33'
  - '@arkade-os/sdk@0.4.28'
  - '@arkade-os/boltz-swap@0.3.34'
  - '@arkade-os/sdk@0.4.29'
peerDependencyRules:
  allowedVersions:
    expo-background-task: '*'
    expo-task-manager: '*'
