import Svg, { Path } from "react-native-svg";

type SparkleProps = {
  size?: number;
  color?: string;
  /** Render only the main sparkle (no companion). Useful when the parent
   *  wants to animate the two pieces on independent timelines. */
  mainOnly?: boolean;
  companionOnly?: boolean;
  companionOpacity?: number;
};

// Path data uses a 1024x1024 viewBox identical to the static PNG icon
// generated by generate_assets.py — so the animation's final frame visually
// matches splash-icon.png exactly. Center: (512, 512). Main radius: 266.24.
// Companion at offset (0.75, -0.55) of radius, scale 0.28.

const MAIN_PATH =
  "M 512 245.76 " +
  "C 554.6 432.13, 591.87 469.4, 778.24 512 " +
  "C 591.87 554.6, 554.6 591.87, 512 778.24 " +
  "C 469.4 591.87, 432.13 554.6, 245.76 512 " +
  "C 432.13 469.4, 469.4 432.13, 512 245.76 Z";

const COMPANION_PATH =
  "M 711.68 291.02 " +
  "C 723.61 343.2, 734.04 353.64, 786.23 365.57 " +
  "C 734.04 377.5, 723.61 387.93, 711.68 440.12 " +
  "C 699.75 387.93, 689.32 377.5, 637.13 365.57 " +
  "C 689.32 353.64, 699.75 343.2, 711.68 291.02 Z";

export function Sparkle({
  size = 200,
  color = "#ffffff",
  mainOnly = false,
  companionOnly = false,
  companionOpacity = 0.9,
}: SparkleProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 1024 1024">
      {!companionOnly && <Path d={MAIN_PATH} fill={color} />}
      {!mainOnly && (
        <Path d={COMPANION_PATH} fill={color} opacity={companionOpacity} />
      )}
    </Svg>
  );
}
